Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/windows-10"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "win10"
      vb.gui = true
      vb.memory = "6240"
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--usb", "on"]
      vb.customize ["modifyvm", :id, "--usbehci", "on"]
    end

    config.vm.network "public_network"
end
